version: 2.1

workflows:
  dev-pipeline:
    jobs:
      - test-frontend
      - test-backend
      - sonar-scan:
          requires:
            - test-frontend
            - test-backend
          filters:
            branches:
              only: dev
