# See https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-parameters/
sonar.projectKey=Abdel1117_Crypto_News
sonar.organization=abdel1117

sonar.sources=frontend/app,backend/app
sonar.tests=frontend/__tests__,backend/tests
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/htmlcov/**,**/__pycache__/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.python.version=3.13
