version: 2.1

jobs:
  deploy:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - checkout
      - run:
          name: Deploy
          command: ssh $HOST_VPS@$IP_VPS 'echo "Connexion au VPS réussi"'
      - run:
          name: Navigate to project directory
          command: ssh $HOST_VPS@$IP_VPS 'cd /opt/app/Crypto_News &&  git checkout prod && git pull'

      - run:
          name: Docker Build
          command: ssh $HOST_VPS@$IP_VPS 'cd /opt/app/Crypto_News && docker compose -f docker-compose-prod.yml build --no-cache'
      - run:
          name: Docker Up
          command: ssh $HOST_VPS@$IP_VPS 'cd /opt/app/Crypto_News && docker compose -f docker-compose-prod.yml up'
      
