version: 2.1

jobs:
  deploy:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - checkout
      - run:
          name: Deploy
          command: ssh $HOST_VPS@$IP_VPS 'echo "Connexion au VPS réussi"'
      - run:
          name: Navigate to project directory
          command: ssh $HOST_VPS@$IP_VPS 'cd $DEPLOY_PATH && git checkout prod && git pull'
      - run: 
          name: Lancement Docker 
          command : ssh @HOST_VPS@$IP_VPS ' cd $DEPLOY_PATH && docker compose up -f docker-compose-prod.yml build --no-cache'

