version: 2.1

jobs:
  sonar-scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    working_directory: ~/project
    steps:
      - checkout : 
          method: full
      - attach_workspace:
          at: ~/project
      - run:
          name: Verify Git repository
          command: |
            git fsck --full
            git rev-parse --is-shallow-repository
      - run:
          name: Run SonarCloud analysis
          command: |
            sonar-scanner \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.branch.name="$CIRCLE_BRANCH"
