version: 2.1

jobs:
  test-frontend:
    docker:
      - image: cimg/node:22.14
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - frontend-deps-v1-{{ checksum "package.json" }}
            - frontend-deps-v1-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: frontend-deps-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run unit tests
          command: npm run coverage
      - persist_to_workspace:
          root: ~/project
          paths:
            - frontend/coverage

  test-backend:
    docker:
      - image: cimg/python:3.12
    working_directory: ~/project/backend
    steps:
      - checkout:
          path: ~/project

      - restore_cache:
          keys:
            - backend-deps-v1-{{ checksum "requirements.txt" }}
            - backend-deps-v1-

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - save_cache:
          key: backend-deps-v1-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip

      - run:
          name: Run unit tests
          command: |
            pytest tests/unit \
              --cov \
              --cov-report=xml:coverage.xml \
              -v

      - persist_to_workspace:
          root: ~/project
          paths:
            - backend/coverage.xml
